name: Publish update on push

'on':
  push:
    branches: ['main']

jobs:
  publish_update:
    type: update
    params:
      branch: preview
      message: 'Update published automatically from GitHub push'
